name: 'macOS DMG'

on:
  workflow_dispatch:
  push:
    branches:
      - 'none'
    paths-ignore:
      - 'docs/**'
      - "*.md"

env:
  APPNAME: USBImager
  UV_SYSTEM_PYTHON: 1
  UV_NO_PROGRESS: 1
  HOMEBREW_NO_INSTALL_CLEANUP: true
  HOMEBREW_NO_ENV_HINTS: true
  HOMEBREW_CLEANUP_MAX_AGE_DAYS: 999
  HOMEBREW_NO_ANALYTICS: true
  HOMEBREW_NO_AUTO_UPDATE: true

jobs:
  build_macos:
    runs-on: ${{ matrix.os }}

    strategy:
      # create-dmg chokes when running parallel workers 
      max-parallel: 1 
      # see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
      matrix:
        os: ['macos-13', 'macos-14']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: true

      - name: set vars
        id: envconf
        run: |
          echo "VERSION=$(git describe --abbrev=0)" >> $GITHUB_ENV
          echo "TAG=$(git describe)" >> $GITHUB_ENV          

      - name: Make project
        working-directory: ./src
        run: make package

      - name: Unzip app
        run: unzip -o *.zip

      - name: Upload Artifacts zip
        uses: actions/upload-artifact@v4
        with:
          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
          overwrite: true
          name: ${{ env.APPNAME }}-${{ matrix.os }}-${{ github.sha }}
          path: |
            **/*.zip

      - name: Create DMG
        if: true
        run: |
          create-dmg --volname "${{ env.APPNAME }}" --volicon src/misc/usbimager.icns --eula src/LICENSE  --app-drop-link 50 50 "{{ env.APPNAME }}-${{ env.TAG }}.dmg" "${{ env.APPNAME }}.app"

      - name: Upload Artifacts DMG
        if: true
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
          # branch name: ${{ github.ref_name }}
          name: DMG-${{ env.APPNAME }}-${{ matrix.os }}-${{ github.sha }}
          path: |
            **/*.dmg
        
