name: msys build

on:
  workflow_dispatch:
  push:
    branches:
      - 'none'
    paths-ignore:
      - 'docs/**'
      - "*.md"

env:
  APPNAME: USBImager

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
      fail-fast: false    
    defaults:
      run:
        shell: bash
    steps:
      - uses: msys2/setup-msys2@v2

        with:
          update: true
          msystem: ${{ matrix.sys}}
          install: >-
            base-devel
            make
            gcc
            zlib
            zlib-devel
            mingw-w64-clang-${{matrix.env}}-zlib
            mingw-w64-${{matrix.env}}-zlib
            mingw-w64-${{matrix.env}}-gcc
            mingw-w64-${{matrix.env}}-gcc-libs
            mingw-w64-${{matrix.env}}-make
            mingw-w64-clang-${{matrix.env}}-make
            zip
            unzip
            
      - name: Checkout full repo with all tags and history
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          
      - name: print env
        run: env

      - name: Build
        working-directory: src
        shell: msys2 {0}
        run: make package
          
      - name: List files
        run: |
          pwd
          echo ${{ github.workspace }}
          ls -alh 
          find .

      # - name: unpack zip package
      #   run: |
      #     find . -iname '*.zip' -exec unzip -o {} \;
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APPNAME }}-${{ matrix.sys}}-${{matrix.env}}
          path: '**/*.zip'

